<?php

# [Claude AI edit] START - this entire file was added as part of the Claude AI
# assisted integration of the "Orbital Command" satellite tracking console.
#
# It serves webpanel/App/Static/orbital-command.html (deployed to
# {web_home}/App/Static/ by install_and_upgrade.sh) at the /satellite URL,
# but ONLY when 'experimental_features: true' is set in config/settings.yml
# (surfaced by Ansible as Config::ENABLE_EXPERIMENTAL_FEATURES). Keeping the
# HTML outside of public/ means the feature flag cannot be bypassed by
# requesting the file directly.

namespace App\Controllers;

use Config\Config;

class SatelliteController extends \Lib\Controller {
  # serve the self-contained orbital tracking console
  public function indexAction($args) {
    # feature flag gate - the defined() guard tolerates a Config.php that was
    # generated by an older Config.php.j2 which predates this constant
    if (!defined('Config\Config::ENABLE_EXPERIMENTAL_FEATURES') ||
        Config::ENABLE_EXPERIMENTAL_FEATURES != 'true') {
      header('Location: /passes');
      exit;
    }

    $html_file = __DIR__ . '/../Static/orbital-command.html';
    if (!file_exists($html_file)) {
      header('HTTP/1.0 404 Not Found');
      echo '404 - orbital-command.html asset is missing';
      exit;
    }

    # inject the configured ground station coordinates so the console centers
    # on this station instead of asking the browser for a location fix
    $observer = json_encode(array(
      'lat'   => floatval(Config::BASE_STATION_LAT),
      'lon'   => floatval(Config::BASE_STATION_LON),
      'label' => 'GROUND STATION',
    ));
    $inject = "<script>window.RN2_OBSERVER = " . $observer . ";</script>\n</head>";

    header('Content-Type: text/html; charset=utf-8');
    echo str_replace('</head>', $inject, file_get_contents($html_file));
  }
}
# [Claude AI edit] END

?>
