---
- name: blacklist dvb modules
  become: yes
  copy:
    src: rtlsdr.conf
    dest: /etc/modprobe.d/rtlsdr.conf
    owner: root
    group: root
    mode: 0644

- name: blacklist Airspy modules
  become: yes
  copy:
    src: airspy-blacklist.conf
    dest: /etc/modprobe.d/airspy-blacklist.conf
    owner: root
    group: root
    mode: 0644

- name: blacklist MiriSDR modules
  become: yes
  copy:
    src: blacklist-msi.conf
    dest: /etc/modprobe.d/blacklist-msi.conf

- name: check if RTL-SDR software is installed
  stat:
    path: /usr/local/bin/rtl_sdr
  register: rtlsdr_bin

- name: git clone RTL-SDR software
  git:
    repo: https://github.com/osmocom/rtl-sdr.git
    dest: /tmp/rtl-sdr
    update: no
  register: rtlsdr
  when: not rtlsdr_bin.stat.exists

- name: create RTL-SDR build directory
  file:
    path: /tmp/rtl-sdr/build
    state: directory
    mode: 0755
  when: rtlsdr.changed

- name: generate build system for RTL-SDR software
  command: cmake ../ -DDETACH_KERNEL_DRIVER=ON
  args:
    chdir: /tmp/rtl-sdr/build
    creates: /tmp/rtl-sdr/build/Makefile
  when: rtlsdr.changed

- name: make RTL-SDR software
  command: make
  args:
    chdir: /tmp/rtl-sdr/build
    creates: /tmp/rtl-sdr/build/src/rtl_sdr
  when: rtlsdr.changed

- name: install RTL-SDR software
  become: yes
  command: make install
  args:
    chdir: /tmp/rtl-sdr/build
    creates: /usr/local/bin/rtl_fm
  when: rtlsdr.changed

- name: link RTL-SDR files
  become: yes
  command: ldconfig
  when: rtlsdr.changed

- name: Unload kernel modules (ignore if error, that means the stock driver wasn't present which is good)
  become: yes
  command: modprobe -r msi2500 msi001
  ignore_errors: yes  # Ignore errors if the modules are not loaded

- name: copy RTL-SDR udev rules
  become: yes
  copy:
    src: /tmp/rtl-sdr/rtl-sdr.rules
    dest: /etc/udev/rules.d/rtl-sdr.rules
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  when: rtlsdr.changed

- name: copy Airspy udev rules
  become: yes
  copy:
    src: 52-airspy.rules
    dest: /etc/udev/rules.d/52-airspy.rules
    owner: root
    group: root
    mode: 0644
...
