#!/bin/bash
#
# Purpose: Creates a pristine image that can later be used in things such as composite images.
#
# Input parameters:
#   1. Input .wav file
#   2. Output -a.jpg file
#   3. Output -b.jpg file
#
# Example:
#   ./noaa_histogram_data.sh  /path/to/input.wav /path/to/output-a.png /path/to/output-b.png 

# import common lib and settings
. "$HOME/.noaa-v2.conf"
. "$NOAA_HOME/scripts/common.sh"

# input params
INPUT_WAV=$1
OUTPUT_IMAGE_A=$2
OUTPUT_IMAGE_B=$3

# produce the output image
$WXTOIMG -o -a -c -e "pristine" "${INPUT_WAV}" "${OUTPUT_IMAGE_A}"
$WXTOIMG -o -b -c -e "pristine" "${INPUT_WAV}" "${OUTPUT_IMAGE_B}"
