#!/bin/bash
#
# Purpose: Creates pristine images of channel a and channel b without telemetry to send to a histogram
#
#
# Input parameters:
#   
#   1. Input .wav file
#   2. Output .a.png file
#   3. Output .b.png file
#
# Example:
#   ./noaa_separate_pristine /path/to/input.wav /path/to/output.a.png /path/to/output.b.png

# import common lib and settings
. "$HOME/.noaa-v2.conf"
. "$NOAA_HOME/scripts/common.sh"

# input params
INPUT_WAV=$1
OUTPUT_IMAGE_A=$2
OUTPUT_IMAGE_B=$3

# produce the output image
$WXTOIMG -o -p -a -c "${INPUT_WAV}" "${OUTPUT_IMAGE_A}"
$WXTOIMG -o -p -b -c "${INPUT_WAV}" "${OUTPUT_IMAGE_B}"
