---
- name: install raspberry-noaa-v2 core
  hosts: core
  connection: local
  gather_facts: no
  pre_tasks:
    - name: get os release
      shell: grep "^deb http://deb.debian.org/debian" /etc/apt/sources.list | head -n 1 | awk '{print $3}'
      register: raspbian_version
      check_mode: no
      changed_when: no
  roles:
    - role: common
...
