---
- name: install raspberry-noaa-v2 core
  hosts: core
  connection: local
  gather_facts: yes
  pre_tasks:
    - name: get os release
      shell: lsb_release -c --short
      register: raspbian_version
      check_mode: no
      changed_when: no
  roles:
    - role: common
...
